spring:

  #
  # DATASOURCE CONFIG
  #
  datasource:
    myapp:
      host: ${SC_HOST:localhost}
      port: ${SC_PORT:5432}
      db: ${SC_DB:myapp}
      user: ${SC_USER:admin}
      currentSchema: ${SC_SCHEMA:public}
      password: ${SC_PASSWORD:admin}
    url: jdbc:postgresql://${spring.datasource.myapp.host}:${spring.datasource.myapp.port}/${spring.datasource.myapp.db}
    driver-class-name: org.postgresql.Driver
    username: ${spring.datasource.myapp.user}
    password: ${spring.datasource.myapp.password}

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  #
  # HIBERNATE CONFIG
  #
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: ${spring.datasource.myapp.currentSchema}
    show-sql: true

    #
    # FlyWay
    #
  flyway:
    enabled: true
    url: jdbc:postgresql://${spring.datasource.myapp.host}:${spring.datasource.myapp.port}/${spring.datasource.myapp.db}
    schemas: ${spring.datasource.myapp.currentSchema}
    default-schema: ${spring.datasource.myapp.currentSchema}
    user: ${spring.datasource.myapp.user}
    password: ${spring.datasource.myapp.password}

app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

